---
#config.yml
#How to add: 1, 0, 64
#          ID, Meta, Count
item1: 257, 0, 1
#name items 1
item1-name: "Pickaxe Iron Pro"

#Items 2
item2: 745, 0, 1
item2-name: "Pickaxe Netherite Pro"

#messenge newbie claim items
itemstart-messenges: "Hello ! I gave you the item when I first joined"
...
